Guidelines on (open) Data
ClimateCompatibleGrowth/guidelines pull request #11
Opened 2022-03-07 17:33 UTC by AgnesBelt

Data guideline, structured as follow:
- Generic intro on open data and data cycle
- Open Science practices pertaining to the release of open data
     - Metadata
     - Referencing
     - Attribution
     - Release
     - License
     - Version control
     - Workflow

@willu47 please let me know how does this look, particularly the references to Version control and Workflow.

2022-03-08 09:13 UTC, willu47 requested changes
Hi @AgnesBelt - looks great. I think it's a good introduction to data outputs, with a clear and concise summary of the basics.

A few thoughts presented inline below.

You could also provide a link to development of a data management plan (for larger projects). For example https://dmponline.dcc.ac.uk/

Also many universities have their own set of public resources about these tools, so it's worth highlighting that researchers can reference these as well.

2022-03-08 09:49 UTC, AgnesBelt commented on _posts/2022-03-06-data.md
> +To ensure all the contributors - i.e. people involved in collecting, processing, structuring and releaseing the data - are acknolwegded, the [CRediT author statement](<https://www.elsevier.com/author
Sure, once we have the blog post to link to we can add the reference. Not sure it exists already...?

2022-03-08 11:28 UTC, AgnesBelt commented on _posts/2022-03-06-data.md
> +    a. *Manually creating a data package*, containing all the necessary information to ensure original data sources, data processing steps and contributors are clearly mentioned. This can be done via
I tried and change it according to the structure you suggested. Not sure if the releasing steps of the generic intro should be removed at this point... and just added under storing and sharing.

2022-03-08 11:28 UTC, AgnesBelt commented on _posts/2022-03-06-data.md
> +1. **Planning**: a plan should be establish in the form of a live document, to identify types of data and related formats that are expected to be used in the project.
changed into subheadingss

2022-03-08 11:28 UTC, AgnesBelt commented on _posts/2022-03-06-data.md
> +Version control systems, such as [Git](<https://git-scm.com/>), and dedicated online services, such as [GitHub](<https://github.com/>), allow to record instances of text-based material and (e.g. data
I added such empty (for now) references under each main subsection about the open practices.

2022-03-08 11:29 UTC, AgnesBelt commented on _posts/2022-03-06-data.md
> +To ensure data are corectly used and managed across research projects, the following process cycle<sup>[1](#myfootnote1)</sup> should be kept in mind:
Is it ok now?

2022-03-08 19:50 UTC, AgnesBelt commented
I did a mess, and added the Attribution guideline under the same branch that I used for the Pull Request related to the Data Guideline. So, now this Pull Request #11 contains both my newly created guidelines for Data and Attribution. Anyway, I guess it's ok for now.

2022-03-09 14:47 UTC, willu47 commented
Haha, easy to do. If you create a new branch (from the previous branch) containing those commits and then a separate pull request you can partially fix this.

Best practice is to always create a new branch from the main branch when starting work on a new topic which avoids such tangles.

2022-03-09 17:42 UTC, AgnesBelt commented
I tried to fix it. I hope I didn't mess it up further now. Attribution guidelines now available in a separate pull request #14

2022-03-15 10:18 UTC, willu47 commented on _posts/2022-03-06-data.md
> +Version control systems, such as [Git](<https://git-scm.com/>), and dedicated online services, such as [GitHub](<https://github.com/>), allow to record instances of text-based material and (e.g. data
You don't need the `<` and `>` around the hyperlinks in markdown.

2022-03-15 10:19 UTC, willu47 reviewed
Suggest adding links to these very useful resources:

[Research Data Management](https://the-turing-way.netlify.app/reproducible-research/rdm.html) section of [The Turing Way](https://the-turing-way.netlify.app/welcome.html)

The entry on [data standards for energy modelling](https://forum.u4ria.org/t/data-standards-for-energy-modeling-for-policy-support/25) at the [u4RIA forum](https://forum.u4ria.org)

2022-03-17 09:26 UTC, AgnesBelt commented
Hi Will, I have now addressed all your comments. Please, see if it is ready to publish. Thanks!

2022-03-21 10:29 UTC, merged